name: docker-compose.dev.yml

services:
  redis:
    image: redis:7-alpine
    healthcheck: 
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  db:
    image: postgres:16
    env_file:
      - .env.docker

    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d inventory_app"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  migrations:
    build: .
    command: npm run migrate:up
    env_file:
      - .env.dev
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  api:
    build:
      context: .
      target: dev
    env_file:
      - .env.dev
      - .env.docker
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    command: sh -c "npm ci && npm run dev"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    restart: "no"
  

volumes:
  postgres_data:
  node_modules:
